//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentManagementSystem_DAL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public long Id { get; set; }
        public System.DateTime BookingFromDate { get; set; }
        public string CustomerName { get; set; }
        public int VehicleId_Fk { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string FromLocation { get; set; }
        public string ToLocation { get; set; }
        public Nullable<int> BookedBy_FK { get; set; }
        public string Shift { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string CNIC { get; set; }
        public string MileageStart { get; set; }
        public string MileageEnd { get; set; }
        public Nullable<int> FuleLtr { get; set; }
        public Nullable<int> Driver1Id_FK { get; set; }
        public Nullable<int> Driver2Id_FK { get; set; }
        public Nullable<int> RentAmount { get; set; }
        public string Notes { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> BookingToDate { get; set; }
        public Nullable<int> Duration { get; set; }
    }
}
