//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentManagementSystem_DAL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CNIC { get; set; }
        public string Address { get; set; }
        public string ContactNo { get; set; }
        public string LicenseType { get; set; }
        public string LicenseNo { get; set; }
        public string City { get; set; }
        public Nullable<int> ExperienceInYears { get; set; }
        public bool IsActive { get; set; }
    }
}
