//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentManagementSystem_DAL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public string Model { get; set; }
        public string RegistredIn { get; set; }
        public string Color { get; set; }
        public bool IsActive { get; set; }
    }
}
